import type { Metadata } from "next";
import { CleanLayout, ProtectedPage } from "@/components";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CleanLayout>
      {/* <ProtectedPage> */}
      {children}
      {/* </ProtectedPage> */}
    </CleanLayout>
  );
}
