import type { Metadata } from "next";
import { BaseLayout, ProtectedPage } from "@/components";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wine Admin Dashboard",
  description: "Generated by Blazar Labs",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <BaseLayout>
      <ProtectedPage>{children}</ProtectedPage>
    </BaseLayout>
  );
}
